#!/usr/bin/env python3
"""
Quick start script to configure BuildEstimate Pro with Supabase
"""
import os
from pathlib import Path


def get_supabase_credentials():
    print("\n" + "="*60)
    print("BuildEstimate Pro - Supabase Configuration")
    print("="*60)
    print("\nEnter your Supabase credentials below.")
    print("You can find these at: https://app.supabase.com/project/[your-project]/settings/api\n")
    
    # Get credentials
    supabase_url = input("Enter Supabase Project URL (e.g., https://xxx.supabase.co): ").strip()
    publishable_key = input("Enter Publishable Key (anon key): ").strip()
    secret_key = input("Enter Secret Key: ").strip()
    
    # Get database password
    print("\nFor DATABASE_URL, you need:")
    print("1. Your Supabase project host (e.g., xxx.db.supabase.co)")
    print("2. Your database password (from Settings > Database)")
    
    db_host = input("\nEnter database host (e.g., xxx.db.supabase.co): ").strip()
    db_password = input("Enter database password: ").strip()
    
    # Get optional Gemini API key
    print("\n(Optional) For PDF Q&A features:")
    gemini_key = input("Enter Gemini API Key (press Enter to skip): ").strip()
    
    return {
        "supabase_url": supabase_url,
        "publishable_key": publishable_key,
        "secret_key": secret_key,
        "db_host": db_host,
        "db_password": db_password,
        "gemini_key": gemini_key,
    }


def create_env_file(credentials):
    """Create .env file with provided credentials"""
    env_content = f"""# BuildEstimate Pro - Environment Configuration
# Generated by setup script

# Supabase Configuration
SUPABASE_URL={credentials['supabase_url']}
SUPABASE_KEY={credentials['publishable_key']}
SUPABASE_SECRET={credentials['secret_key']}

# PostgreSQL Connection String
DATABASE_URL=postgresql://postgres:{credentials['db_password']}@{credentials['db_host']}:5432/postgres

# API Configuration
API_URL=http://127.0.0.1:8000

# Gemini API Key (optional)
"""
    
    if credentials['gemini_key']:
        env_content += f"GEMINI_API_KEY={credentials['gemini_key']}\n"
    else:
        env_content += "# GEMINI_API_KEY=your-key-here\n"
    
    # Write to .env file in project root
    project_root = Path(__file__).parent
    env_file = project_root / ".env"
    
    with open(env_file, "w") as f:
        f.write(env_content)
    
    return env_file


def verify_connection():
    """Verify database connection"""
    print("\n" + "="*60)
    print("Verifying Supabase Connection...")
    print("="*60)
    
    try:
        from dotenv import load_dotenv
        from sqlalchemy import create_engine, text
        
        load_dotenv()
        
        db_url = os.getenv("DATABASE_URL")
        if not db_url:
            print("❌ DATABASE_URL not set in .env")
            return False
        
        print(f"Attempting to connect to: {db_url.split('@')[1] if '@' in db_url else 'Unknown'}")
        
        engine = create_engine(db_url)
        with engine.connect() as conn:
            result = conn.execute(text("SELECT version()"))
            version = result.fetchone()[0]
            print(f"✅ Connected successfully!")
            print(f"   PostgreSQL: {version}")
            return True
            
    except Exception as e:
        print(f"❌ Connection failed: {str(e)}")
        print("\nTroubleshooting:")
        print("1. Verify credentials are correct")
        print("2. Check Supabase project is running")
        print("3. Ensure firewall allows port 5432")
        return False


def init_database():
    """Initialize database tables"""
    print("\n" + "="*60)
    print("Initializing Database Tables...")
    print("="*60)
    
    try:
        from buildestimate_pro.scripts.seed_database import seed
        
        print("Creating tables and seeding demo data...")
        seed()
        print("✅ Database initialized successfully!")
        return True
        
    except Exception as e:
        print(f"❌ Database initialization failed: {str(e)}")
        return False


def main():
    print("\n" + "🏗️ "*15)
    print("Welcome to BuildEstimate Pro Setup")
    print("🏗️ "*15 + "\n")
    
    # Get credentials
    credentials = get_supabase_credentials()
    
    # Create .env file
    print("\n" + "="*60)
    print("Creating .env file...")
    print("="*60)
    
    try:
        env_file = create_env_file(credentials)
        print(f"✅ .env file created at: {env_file}")
    except Exception as e:
        print(f"❌ Failed to create .env file: {str(e)}")
        return
    
    # Verify connection
    if not verify_connection():
        print("\n⚠️  Connection verification failed.")
        print("Please check your credentials and try again.")
        return
    
    # Initialize database
    if not init_database():
        print("\n⚠️  Database initialization failed.")
        print("You may need to check your database setup.")
        return
    
    # Success
    print("\n" + "="*60)
    print("✅ Setup Complete!")
    print("="*60)
    print("""
Next steps:

1. Start the Backend:
   cd buildestimate_pro
   python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000

2. Start the Frontend (in new terminal):
   cd buildestimate_pro
   streamlit run frontend/app.py --server.port 8501

3. Open in browser:
   Frontend: http://localhost:8501
   API Docs: http://localhost:8000/docs

Happy Estimating! 🚀
""")


if __name__ == "__main__":
    main()
